<script lang="ts">
  import { drawerStore, type DrawerSettings } from '@skeletonlabs/skeleton'
  import { AlertTriangle, Check, CheckCircle2, Dices } from 'lucide-svelte'
  import type { Addon, Game } from 'shared'
  import games from 'shared/games'
  import thumbnailFallback from '../../assets/addon-thumbnail-fallback.jpg'
  import { activeProfileStore } from '../../stores/active-profile'
  import { conflictGroups } from '../../stores/conflicts'
  import {
    librarySelectedAddonIds,
    libraryActiveAddons,
    libraryAddonIdsInEnabledShuffles,
    unsubscribedItemsThisSession,
    installedAddons,
    isDraggingAddon,
    addonOverviewId,
    libraryActiveSubCategories
  } from '../../stores/library'
  import { userStore } from '../../stores/user'
  import { L4D2_GAME_ID } from '../../utils'
  import { db } from '../../db/db'
  const handleMissingThumbnail = (ev) => (ev.target.src = thumbnailFallback)

  export let addon: Addon
  export let asShuffle: boolean = false
  export let mode: 'in-shuffle-list' | 'card' | 'list'

  // Thumbnail based on the active game id, and if it's from the workshop
  $: activeGameId = L4D2_GAME_ID
  $: activeGameDetails = games[activeGameId] as Game
  $: thumbnail =
    `file:///${$userStore.steamGamesDir}/common/${activeGameDetails.rootDirectoryName}/${activeGameDetails.gameDirectory}/addons/${addon.id}`.replace(
      'vpk',
      'jpg'
    )
  $: isEnabled = $libraryActiveAddons.includes(addon.id)
  $: isShuffled = $libraryAddonIdsInEnabledShuffles.includes(addon.id)
  $: isConflicting = $conflictGroups.some((group) =>
    group.some((conflictingMod) => conflictingMod.id == addon.id)
  )
  $: wasUnsubscribed = $unsubscribedItemsThisSession.includes(addon.id)
  $: isInstalled = $installedAddons.includes(addon.id)

  $: selected = $librarySelectedAddonIds.includes(addon.id)
  $: otherModsSelectedButNotThisOne = $librarySelectedAddonIds.some((id) => id != addon.id)
  $: userIsSelecting = $librarySelectedAddonIds.length > 0

  async function toggleModEnable() {
    if (isShuffled) {
      // If the user clicks on a shuffled addon card in a sub category, we remove it from the sub category shuffle
      if ($libraryActiveSubCategories.length == 1) {
        const subCategoryShuffle = await db.shuffles
          .where('autoGeneratedForSubCategory')
          .equals($libraryActiveSubCategories[0])
          .and((sh) => sh.autoGeneratedForProfileId === $activeProfileStore.id)
          .first()
        if (!subCategoryShuffle) return

        const currentlyEnabledAddons = subCategoryShuffle.shuffledAddonIds

        await db.shuffles.update(subCategoryShuffle.id, {
          shuffledAddonIds: currentlyEnabledAddons.filter((id) => id != addon.id)
        })
      }

      return
    }

    activeProfileStore.toggleAddonEnabled(addon.id)
  }

  function dragStart(event) {
    $isDraggingAddon = true
    const data = { addonId: addon.id }
    event.dataTransfer.setData('text/plain', JSON.stringify(data))
  }

  function dragEnd(event) {
    event.preventDefault()
    $isDraggingAddon = false
  }

  function openOverview() {
    $addonOverviewId = addon.id

    const settings: DrawerSettings = {
      id: 'addon-overview',
      width: 'w-[50%] max-w-[600px]',
      rounded: 'rounded-none'
    }

    drawerStore.open(settings)
  }

  function handleClick(e: MouseEvent) {
    if (!e.ctrlKey) {
      if (!userIsSelecting) {
        toggleModEnable()
        return
      }
    }

    librarySelectedAddonIds.update((addons) => {
      if (addons.includes(addon.id)) {
        return addons.filter((id) => id != addon.id)
      } else {
        return [...addons, addon.id]
      }
    })
  }

  // handleShiftMouseEnter
  function handleMouseEnter(e: MouseEvent) {
    //if (uninstalled) return

    if (!e.shiftKey) return
    if (!e.ctrlKey) return

    // toggle mod selection
    librarySelectedAddonIds.update((addons) => {
      if (addons.includes(addon.id)) {
        return addons.filter((id) => id != addon.id)
      } else {
        return [...addons, addon.id]
      }
    })
  }

  const tagStyle =
    'absolute items-center justify-center shadow-md font-bold uppercase -bottom-1 rounded-full backdrop-blur-md w-[60%] py-1 text-[12px] left-[50%] translate-x-[-50%] hidden'

  const tagStyleList =
    ' inline items-center justify-center shadow-md font-bold uppercase -bottom-1 rounded-full px-4 py-1 text-[12px] hidden'
</script>

{#if mode == 'in-shuffle-list'}
  <div
    draggable={true}
    on:dragstart={dragStart}
    on:dragend={dragEnd}
    on:contextmenu={openOverview}
    class="flex items-center gap-2"
    class:unsubscribed={wasUnsubscribed}
  >
    <img
      alt="mod"
      on:error={handleMissingThumbnail}
      class="shadow-md rounded-md w-[64px] aspect-[16/9]"
      src={thumbnail}
    />

    <span class="text-sm">{addon.addonInfo.title}</span>
  </div>
{:else if mode == 'card'}
  <button
    on:mouseenter={handleMouseEnter}
    draggable={true}
    on:dragstart={dragStart}
    on:dragend={dragEnd}
    on:contextmenu={openOverview}
    class:selected
    class:unselected={otherModsSelectedButNotThisOne && !selected}
    class="relative -shadow-md transition-transform group"
    class:enabled={isEnabled}
    class:asShuffle
    class:unsubscribed={wasUnsubscribed}
    on:click={handleClick}
  >
    {#if $userStore.thumbnailsWastedSpace !== 'stretch'}
      <div
        data-aspect={$userStore.thumbnailsPreferredAspectRatio}
        data-black={$userStore.thumbnailsWastedSpace == 'fill-black'}
        class="relative data-[aspect=square]:aspect-[1/1] data-[aspect=wide]:aspect-[16/9] data-[black=true]:bg-black w-full rounded-md overflow-hidden"
      >
        {#if $userStore.thumbnailsWastedSpace == 'fill-blur'}
          <img
            alt=""
            on:error={handleMissingThumbnail}
            class="h-full w-full absolute inset-0 blur-lg -z-10 opacity-50 scale-110"
            src={thumbnail}
          />
        {/if}

        <div
          data-aspect={$userStore.thumbnailsPreferredAspectRatio}
          class="absolute inset-0 flex items-center data-[aspect=square]:flex-col justify-center"
        >
          <img
            data-aspect={$userStore.thumbnailsPreferredAspectRatio}
            class="data-[aspect=wide]:max-h-[100%] data-[aspect=wide]:my-auto"
            alt=""
            on:error={handleMissingThumbnail}
            src={thumbnail}
          />
        </div>
      </div>
    {:else}
      <img
        alt=""
        data-aspect={$userStore.thumbnailsPreferredAspectRatio}
        on:error={handleMissingThumbnail}
        class=" rounded-md data-[aspect=square]:aspect-[1/1] data-[aspect=wide]:aspect-[16/9] w-full"
        src={thumbnail}
      />
    {/if}

    {#if selected}
      <div
        class="selected-overlay absolute inset-0 bg w-full h-full right-0 justify-center items-center flex"
      >
        <div class="backdrop-blur-lg rounded-full">
          <CheckCircle2 size={64} />
        </div>
      </div>
    {/if}

    {#if !asShuffle}
      <div class={tagStyle} class:addonEnabled={isEnabled}>
        <Check class="w-4 mr-2" />
        Enabled
      </div>

      <div class={tagStyle} class:addonConflicting={isConflicting}>
        <AlertTriangle class="w-4 mr-2" />
        Conflicting
      </div>

      <div class={tagStyle} class:addonUninstalled={!isInstalled}>
        <AlertTriangle class="w-4 mr-2" />
        Uninstalled
      </div>

      <div class={tagStyle} class:addonShuffled={isShuffled}>
        <Dices class="w-4 mr-2" />
        Shuffle
      </div>
    {/if}
  </button>
{:else if mode == 'list'}
  <button
    on:mouseenter={handleMouseEnter}
    draggable={true}
    on:dragstart={dragStart}
    on:dragend={dragEnd}
    on:contextmenu={openOverview}
    class:selected
    class:unselected={otherModsSelectedButNotThisOne && !selected}
    class="relative shadow-md transition-transform p-2 bg-surface-700 rounded-md"
    class:enabled={isEnabled}
    class:asShuffle
    class:unsubscribed={wasUnsubscribed}
    on:click={handleClick}
  >
    <div class=" flex gap-2">
      <img
        alt="mod"
        on:error={handleMissingThumbnail}
        class=" rounded-md aspect-[16/9] w-[96px]"
        src={thumbnail}
      />

      <div class="text-left flex flex-col justify-between">
        <p>{addon.addonInfo.title}</p>

        <div class="flex">
          {#if !asShuffle}
            <div class={tagStyleList} class:addonEnabled={isEnabled && !isConflicting}>
              <Check class="w-4 mr-2" />
              Enabled
            </div>

            <div class={tagStyleList} class:addonConflicting={isConflicting}>
              <AlertTriangle class="w-4 mr-2" />
              Conflicting
            </div>

            <div class={tagStyleList} class:addonUninstalled={!isInstalled}>
              <AlertTriangle class="w-4 mr-2" />
              Uninstalled
            </div>

            <div class={tagStyleList} class:addonShuffled={isShuffled}>
              <Dices class="w-4 mr-2" />
              Shuffle
            </div>
          {/if}
        </div>
      </div>

      {#if selected}
        <div
          class="selected-overlay absolute inset-0 bg w-full h-full right-0 justify-center items-center flex"
        >
          <div class="backdrop-blur-lg rounded-full">
            <CheckCircle2 size={64} />
          </div>
        </div>
      {/if}
    </div>
  </button>
{/if}

<style lang="postcss">
  .selected {
    outline: 1px solid #6abcffc0;
    @apply outline-primary-500;
    border-radius: 2px;
    opacity: 0.9;

    box-shadow: 0 0 16px 3px #ffffff23;
  }

  .unsubscribed {
    filter: grayscale(100%);
    opacity: 0.5;
    transform: scale(0.8);
  }

  .unselected {
    opacity: 0.5;
    transform: scale(0.8);
  }

  .addonEnabled {
    @apply bg-green-700/80 flex;
  }

  .addonShuffled {
    @apply bg-blue-800/80 flex;
  }

  .addonConflicting {
    @apply bg-orange-600/60 flex;
  }

  .asShuffle {
    @apply min-w-[120px] max-w-[120px]  aspect-[16/9];
  }

  .addonUninstalled {
    @apply bg-red-600/60 flex;
  }
</style>
