import Dexie, { type EntityTable } from 'dexie'

interface Profile {
  id: number
  label: string
  enabledAddonIds: string[]
  enabledShuffleIds: number[]
}

interface Shuffle {
  id: number
  label: string
  shuffledAddonIds: string[]

  // Certain subcategories support auto-generated shuffles
  // These are tied to a profile and subcategory
  autoGeneratedForProfileId?: number
  autoGeneratedForSubCategory?: string

  // If true, there's a chance that no item will be selected from a shuffle
  allowNone?: boolean
}

export interface Startup {
  id: number

  /**
   * The date at which Funky launched the gamme
   */
  date: Date

  /**
   * If the user reported the game as a crash
   */
  reportedAsCrash?: boolean

  /**
   * The playlist the game was run with
   */
  playlistId: number

  /**
   * All the enabled mods the game launched with (post-shuffling)
   */
  enabledModIds: string[]
}

export type CreateStartupPayload = Pick<Startup, 'playlistId' | 'enabledModIds'>
export type UpdateStartupPayload = Pick<Startup, 'id' | 'playlistId' | 'enabledModIds'>

const db = new Dexie('FunkyDatabase-v6') as Dexie & {
  profiles: EntityTable<Profile, 'id'>
  shuffles: EntityTable<Shuffle, 'id'>
  startups: EntityTable<Startup, 'id'>
}

// Schema declaration:
db.version(1).stores({
  profiles: '++id, *enabledAddonIds, *enabledShuffleIds',
  shuffles: '++id, *shuffledAddonIds, autoGeneratedForProfileId, autoGeneratedForSubCategory'
})

// Schema declaration:
db.version(2).stores({
  startups: '++id, date, reportedAsCrash, playlistId'
})

// Populate the database with default, empty profiles
db.on('populate', async () => {
  db.profiles.add({
    id: 1,
    label: 'Default',
    enabledAddonIds: [],
    enabledShuffleIds: []
  })

  db.profiles.add({
    id: 2,
    label: 'No Mods',
    enabledAddonIds: [],
    enabledShuffleIds: []
  })
})

export type { Profile, Shuffle }
export { db }
